services:
  - type: web
    name: nlg-flask-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    branch: main
    autoDeploy: true
