services:
  - type: web
    name: text-prediction-api
    env: python
    plan: free
    build:
      commands:
        - pip install -r requirements.txt
    deploy:
      commands:
        - python model.py  # Dit traint en slaat het model op
    routes:
      - type: http
        port: 10000
