services:
  - type: web
    name: pyrender-nlg
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    branch: main
    autoDeploy: true
