services:
  - type: web
    name: woordvoorspeller
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    instances: 1
    envVars:
      - key: PORT
        value: "8080"
