services:
  - type: web
    name: jouw-app-naam
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:8070
    plan: free
    autoDeploy: true
